/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_GUI;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author user
 */
public class MainMenu_GUI extends javax.swing.JFrame {

    LoginGUI viewLogin = new LoginGUI();
    ClientMenu ClientMenu = new ClientMenu();
    ManajerMenu ManajerMenu = new ManajerMenu();
    ProgrammerMenu ProgrammerMenu = new ProgrammerMenu();
    ProyekMenu ProyekMenu = new ProyekMenu();
    
    CardLayout view;

    public MainMenu_GUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        view = (CardLayout) panelLayout.getLayout();
//        view = (CardLayout) jPanel1.getLayout();

    }

    public LoginGUI getViewLogin() {
        return viewLogin;
    }

    public void setViewLogin(LoginGUI viewLogin) {
        this.viewLogin = viewLogin;
    }

    public JToggleButton getBtnClient() {
        return btnClient;
    }

    public void setBtnClient(JToggleButton btnClient) {
        this.btnClient = btnClient;
    }

    public JToggleButton getBtnManajer() {
        return btnManajer;
    }

    public void setBtnManajer(JToggleButton btnManajer) {
        this.btnManajer = btnManajer;
    }

    public JToggleButton getBtnProgrammer() {
        return btnProgrammer;
    }

    public void setBtnProgrammer(JToggleButton btnProgrammer) {
        this.btnProgrammer = btnProgrammer;
    }

    public JToggleButton getBtnProyek() {
        return btnProyek;
    }

    public void setBtnProyek(JToggleButton btnProyek) {
        this.btnProyek = btnProyek;
    }

    public JButton getBtnlogout() {
        return btnlogout;
    }

    public void setBtnlogout(JButton btnlogout) {
        this.btnlogout = btnlogout;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JPanel getjPanel7() {
        return jPanel7;
    }

    public void setjPanel7(JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ClientMenu_view = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClient = new javax.swing.JToggleButton();
        btnManajer = new javax.swing.JToggleButton();
        btnProgrammer = new javax.swing.JToggleButton();
        btnProyek = new javax.swing.JToggleButton();
        btnlogout = new javax.swing.JButton();
        panelLayout = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        ClientMenu_view.setBackground(new java.awt.Color(204, 0, 0));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Welcome !");

        btnClient.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/client.png"))); // NOI18N
        btnClient.setText("Client");
        btnClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClient.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClient.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });

        btnManajer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnManajer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/manajer.png"))); // NOI18N
        btnManajer.setText("Manajer");
        btnManajer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManajer.setPreferredSize(new java.awt.Dimension(100, 30));
        btnManajer.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnManajer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManajer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajerActionPerformed(evt);
            }
        });

        btnProgrammer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnProgrammer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/programmer.png"))); // NOI18N
        btnProgrammer.setText("Programmer");
        btnProgrammer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProgrammer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProgrammer.setPreferredSize(new java.awt.Dimension(100, 30));
        btnProgrammer.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnProgrammer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProgrammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgrammerActionPerformed(evt);
            }
        });

        btnProyek.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnProyek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/proyek.png"))); // NOI18N
        btnProyek.setText("Proyek");
        btnProyek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProyek.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProyek.setPreferredSize(new java.awt.Dimension(100, 30));
        btnProyek.setVerifyInputWhenFocusTarget(false);
        btnProyek.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnProyek.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProyek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProgrammer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addComponent(btnClient, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManajer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        panelLayout.setBackground(new java.awt.Color(204, 0, 0));
        panelLayout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLayout.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout ClientMenu_viewLayout = new javax.swing.GroupLayout(ClientMenu_view);
        ClientMenu_view.setLayout(ClientMenu_viewLayout);
        ClientMenu_viewLayout.setHorizontalGroup(
            ClientMenu_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientMenu_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addContainerGap())
        );
        ClientMenu_viewLayout.setVerticalGroup(
            ClientMenu_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientMenu_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientMenu_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ClientMenu_viewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnlogout))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClientMenu_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ClientMenu_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyekActionPerformed
        panelLayout.add(ProyekMenu, "Proyek");
        view.show(panelLayout, "Proyek");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();   
    }//GEN-LAST:event_btnProyekActionPerformed

    private void btnManajerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajerActionPerformed
        panelLayout.add(ManajerMenu, "Manajer");
        view.show(panelLayout, "Manajer");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();        
    }//GEN-LAST:event_btnManajerActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        panelLayout.add(ClientMenu, "Client");
        view.show(panelLayout, "Client");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnClientActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnProgrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgrammerActionPerformed
        panelLayout.add(ProgrammerMenu, "Programmer");
        view.show(panelLayout, "Programmer");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();   
    }//GEN-LAST:event_btnProgrammerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientMenu_view;
    private javax.swing.JToggleButton btnClient;
    private javax.swing.JToggleButton btnManajer;
    private javax.swing.JToggleButton btnProgrammer;
    private javax.swing.JToggleButton btnProyek;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelLayout;
    // End of variables declaration//GEN-END:variables
}
